const str = 'Hello, World!'
console.log(str.length)
console.log(str.toUpperCase())
console.log(str.toLowerCase())
console.log(str.indexOf('l'))
console.log(str.lastIndexOf('l'))
console.log(str.includes('He'))
console.log(str.startsWith('Wo'))
console.log(str.endsWith('ld!'))
console.log(str.trim())
console.log(str.slice(0,5))
console.log(str.slice(-5,-2))
console.log(str.substring(0,5))
console.log(str.substring(-2,6))
console.log(str.split(','))
console.log(str.split(' '))
console.log(str.concat(' World!'))
console.log(str.charAt(0))
console.log(str.charCodeAt(0))
console.log(str.search('W'))
console.log(str.replace('Hello', 'Hi'))
console.log(str.padStart(20,'*'))