console.log(typeof "Hello, World!");
console.log(typeof 1);
console.log(typeof 1.1);
console.log(typeof true);
console.log(typeof false);
console.log(typeof null);
console.log(typeof undefined);
console.log(typeof [1, 2, 3]);
console.log(typeof {name: "John", age: 30});
console.log(typeof new Date());
console.log(typeof function() {});
console.log(typeof /abc/);
console.log(typeof NaN);
console.log(typeof Infinity);
console.log(typeof Symbol());
console.log(typeof 123n);    